### ISSUE TITLE
Saving audio w/o using speaker and microphone

### ISSUE THREAD

**Issue by The-Gupta** [guest271314/SpeechSynthesisRecorder#10]
@guest271314 I don't understand the JS code well. 
Is there an easy way to save the output audio file without first playing and then recording? 
Also, is there a python wrapper around this library that I could not find?

**Comment by guest271314** [comment]
@The-Gupta You can use a local server or [Native Messaging](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) to post plain text or SSML to `espeak`, `espeak-ng`, or other speech synthesis binary, then return the response as a `data URL`, see https://stackoverflow.com/q/48219981.

The code at this repository is written in JavaScript.

**Comment by guest271314** [comment]
See also https://freebsoft.org/doc/speechd/speech-dispatcher.html#Python-API
