### ISSUE TITLE
audioBuffer() not working in chrome

### ISSUE THREAD

**Issue by aahedi** [guest271314/SpeechSynthesisRecorder#15]
`.then(ab => this.audioContext.decodeAudioData(ab))`

Uncaught (in promise) TypeError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.

**Comment by guest271314** [comment]
What does `console.log(ab)` print?

**Comment by guest271314** [comment]
Cannot reproduce.

**Comment by guest271314** [comment]
@aahedi See https://github.com/guest271314/SpeechSynthesisRecorder/issues/13
