### ISSUE TITLE
Uncaught TypeError: Failed to set the 'volume' property on 'SpeechSynthesisUtterance': The provided float value is non-finite.

### ISSUE THREAD

**Issue by cn-fanfare** [guest271314/SpeechSynthesisRecorder#16]
error in Chrome 83.

    SpeechSynthesisRecorder.js:45 Uncaught TypeError: Failed to set the 'volume' property on 'SpeechSynthesisUtterance': The provided float value is non-finite.
        at Function.assign (<anonymous>)
        at new SpeechSynthesisRecorder (SpeechSynthesisRecorder.js:45)
        at <anonymous>:1:1

run code.

    new SpeechSynthesisRecorder({
        text: 'The revolution will not be televised',
        utteranceOptions: {
            voice: 'english-us espeak',
            lang: 'en-US',
            pitch: 0.75,
            rate: 1,
        },
    })
        .start()
        .then((tts) => tts.blob())
        .then(({ tts, data }) => {
            // `data` : `Blob`
            tts.audioNode.src = URL.createObjectURL(data);
            tts.audioNode.title = tts.utterance.text;
            tts.audioNode.onloadedmetadata = () => {
                console.log(tts.audioNode.duration);
                tts.audioNode.play();
            };
        });

**Comment by guest271314** [comment]
Does setting volume to `1` at `utteranceOptions` change result?

**Comment by dfriesen1183** [comment]
It did for me
